In [2]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv('vendas_tech.csv', low_memory=False)
display(df_vendas)
df_gerentes = pd.read_excel('gerentes_lojas.xlsx')
display(df_gerentes)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [3]:
# inspecao

display(df_vendas)
display(df_vendas.head(15))
display(df_vendas.columns)
display(df_vendas.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN
10,11,2023-06-28,RIO DE JANEIRO,Smartphone Samsung,2200.0,1,Cliente_3253,NaN
11,12,2024-01-29,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_586,NaN
12,13,2024-06-25,Recife,Smartphone Samsung,2200.0,1,Cliente_4301,NaN
13,14,2023-04-13,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_22985,NaN
14,15,2023-06-23,Curitiba,Cabo HDMI,40.0,1,Cliente_27383,NaN

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente', 'Data_Base'],
      dtype='str')

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

In [4]:
# tratamento de dados
# display(df_vendas['Loja'])
df_novo = df_vendas[['Loja', 'Produto']]
# display(df_novo)

# colunas
df_analise = df_vendas.drop(columns=['Data_Base'])

# nulos
# df_analise = df_analise.dropna() exclui todas linhas com pelo menos 1 valor vazio
df_analise["Loja"] = df_analise["Loja"].fillna("Sem Loja") # preenche os valores vazios com "Sem Loja"

# tipo de dados
df_analise['Data'] = pd.to_datetime(df_analise['Data'], format="%Y-%m-%d")

# padronizacao
df_analise['Loja'] = df_analise['Loja'].str.strip()
df_analise['Loja'] = df_analise['Loja'].str.title()

# encadeamento
# df_analise["Loja"] = df_analise["Loja"].fillna("Sem Loja").str.strip().str.title()

# duplicatas
df_analise = df_analise.drop_duplicates(subset=['ID_Pedido', 'Loja'], keep='first').reset_index(drop=True)

display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Sem Loja,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

In [5]:
# criar novas colunas

# faturamento
df_analise['Faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario']

# forma de venda
df_analise['Forma_de_venda'] = np.where(df_analise['Loja'] == 'Sem Loja', 'Online', 'Presencial')

# regiao
display(df_analise['Loja'].unique())

dic_regioes = {
    'São Paulo': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Sem Loja': 'Online',
    'Rio De Janeiro': 'Sudeste',
    'Salvador': 'Nordeste',
    'Recife': 'Nordeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul'
}
df_analise['Regiao'] = df_analise['Loja'].map(dic_regioes)

display(df_analise)

<StringArray>
[     'São Paulo', 'Belo Horizonte',       'Sem Loja', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Sem Loja,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

In [6]:
# analisar - filtrar
df_analise = df_analise.sort_values(by=['Data', 'Faturamento'], ascending=True)
df_analise = df_analise.reset_index(drop=True) # drop joga o indice antigo fora

# .loc: id do pedido -> localiza por nome da coluna e nome da linha
id_pedido = 4

loja = df_analise.loc[3, 'Loja'] # nome do indice, coluna
cliente = df_analise.loc[3, 'Cliente']
produto = df_analise.loc[3, 'Produto']
# print(loja, cliente, produto)

# .iloc -> por posicao
id_pedido = 4
loja = df_analise.iloc[3, 2] # posicao, numero da coluna
produto = df_analise.iloc[3, 3]
cliente = df_analise.iloc[3, 6]
# print(loja, cliente, produto)

# condicional
df_id_pedido_4 = df_analise[df_analise['ID_Pedido'] == 4]

# exportar pedacos da base
df_vendas_sp = df_analise[df_analise['Loja'] == 'São Paulo']
df_vendas_sp.to_csv('Vendas_SP', index=False)
# display(df_vendas_sp)

# exportas vendas de 2024
df_vendas_2024 = df_analise[df_analise['Data'] >= '2024-01-01']

# duplas condicoes
condicao = df_analise['Produto'] == 'Cabo HDMI'
condicao2 = df_analise['Regiao'] == 'Sul'

df_vendas_hdmi_sul = df_analise[(condicao) & (condicao2)] # para usar ou é |
display(df_vendas_hdmi_sul)

display(df_vendas_2024)
display(df_analise)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Regiao
0,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,40.0,Presencial,Sul
2,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,40.0,Presencial,Sul
3,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
4,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
9,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99874,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
99875,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul
99880,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Presencial,Sul
99881,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Presencial,Sul
99882,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Presencial,Sul

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Regiao
50423,22735,2024-01-01,São Paulo,Cabo HDMI,40.0,1,Cliente_14772,40.0,Presencial,Sudeste
50424,31751,2024-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_16439,40.0,Presencial,Sul
50425,36481,2024-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_4025,40.0,Presencial,Nordeste
50426,44184,2024-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_1577,40.0,Presencial,Sul
50427,44259,2024-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_1944,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,94455,2024-12-30,Curitiba,Notebook Dell,3500.0,2,Cliente_17419,7000.0,Presencial,Sul
99997,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,11000.0,Presencial,Nordeste
99998,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,11000.0,Presencial,Sudeste
99999,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,11000.0,Presencial,Nordeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Regiao
0,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,40.0,Presencial,Sul
1,12848,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_4327,40.0,Presencial,Sudeste
2,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,40.0,Presencial,Sul
3,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
4,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,94455,2024-12-30,Curitiba,Notebook Dell,3500.0,2,Cliente_17419,7000.0,Presencial,Sul
99997,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,11000.0,Presencial,Nordeste
99998,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,11000.0,Presencial,Sudeste
99999,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,11000.0,Presencial,Nordeste

In [15]:
# analiser de agrupamento
analise_loja = df_analise[['Loja', 'Faturamento']].groupby('Loja').sum()
analise_loja = analise_loja.sort_values(by='Faturamento', ascending=False)
analise_loja = analise_loja.reset_index()
analise_loja['Faturamento'] = analise_loja['Faturamento'].map('R$ {:,.2f}'.format)

display(analise_loja)

# ranking de produtos online
df_vendas_online = df_analise[df_analise['Loja'] == 'Sem Loja']
analise_produtos_online = df_vendas_online[['Produto', 'Qtd']].groupby('Produto').sum().sort_values(by='Qtd', ascending=False)

analise_produtos_online = analise_produtos_online.rename(columns={'Qtd': 'Vendas totais'})
display(analise_produtos_online)

# análise de ranking por loja e produto
# quais produtos venderam mais em quais lojas
analise_produtos_em_lojas = df_analise[['Loja', 'Produto', 'Qtd']].groupby(['Loja', 'Produto']).sum()

with pd.option_context('display.max_rows', None):
    display(analise_produtos_em_lojas)

             Loja       Faturamento
0        Salvador  R$ 42,300,610.00
1  Rio De Janeiro  R$ 42,294,720.00
2          Recife  R$ 42,190,390.00
3       São Paulo  R$ 42,090,690.00
4  Belo Horizonte  R$ 41,714,890.00
5    Porto Alegre  R$ 41,678,460.00
6        Curitiba  R$ 41,121,720.00
7        Sem Loja   R$ 6,080,850.00

                    Vendas totais
Produto
Notebook HP                   442
Cabo HDMI                     403
iPhone 14                     390
Mouse Gamer                   379
Notebook Dell                 369
Teclado Mecânico              343
Monitor 27"                   332
Smartphone Samsung            311

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
Sem Loja       Cabo HDMI            403
               Monitor 27"          332
               Mouse Gamer          379
               Notebook Dell        369
               Notebook HP          442
               Smartphone Samsung   311
               Teclado Mecânico     343
               iPhone 14            390
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735